meta_product_name: "Will-Le-Mono"
meta_title: "Will-Le-Mono"
meta_description: "Coach ton permis, et pas que..."
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
